In [9]:
import numpy as  np
arr=np.array([1,2,4,np.nan,np.nan,6])
new_arr=np.nan_to_num(arr,nan=10)
print(new_arr)
print(np.isnan(arr))
print(np.nan!=np.nan)

[ 1.  2.  4. 10. 10.  6.]
[False False False  True  True False]
True


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,65,9,-np.inf,np.inf])
print(np.isinf(arr))
cleaned_arr=np.nan_to_num(arr,posinf=100,neginf=-100)
print(cleaned_arr)

[False False False False False False False  True  True]
[   1.    2.    3.    4.    5.   65.    9. -100.  100.]


In [3]:
import numpy as np
arr=np.array([11,20,30,40,50,56])
arr=arr.reshape(2,3)

print(arr)
arr=np.insert(arr,2,[12,56,34],axis=0)
print(arr)

[[11 20 30]
 [40 50 56]]
[[11 20 30]
 [40 50 56]
 [12 56 34]]


In [4]:
import numpy as np
temp=np.array([34.2,23.0,78,93.8,27.2,28.8])
aver=np.mean(temp)
print(aver)

47.5


In [5]:
import numpy as np
arr=np.array([11,20,30,40,50,56])
arr=arr.reshape(2,3)

print(arr)
arr=np.insert(arr,2,[12,56,34],axis=0)
print(arr)

[[11 20 30]
 [40 50 56]]
[[11 20 30]
 [40 50 56]
 [12 56 34]]
